name: Build sing-box

on:
  workflow_dispatch:    # Ручной запуск
  schedule:
    - cron: '0 0 * * *' # Каждый день в 00:00 UTC

jobs:
  build-and-release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout SagerNet/sing-box
        uses: actions/checkout@v4
        with:
          repository: SagerNet/sing-box
          ref: ${{ github.event.inputs.version || 'main' }} # Используйте тег или ветку

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.24.3'

      - name: Download dependencies
        run: |
          go mod download
          echo "Зависимости загружены"

      - name: Build sing-box for amd64
        run: |
          TAGS="with_gvisor,with_quic,with_dhcp,with_wireguard,with_utls,with_acme,with_clash_api,with_tailscale,with_v2ray_api"
          VERSION="${{ github.event.inputs.version || 'dev' }}-custom"
          GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -v -trimpath -tags "$TAGS" \
            -ldflags "-s -buildid= -X 'github.com/sagernet/sing-box/constant.Version=$VERSION'" \
            -o sing-box_linux_amd64 ./cmd/sing-box
          echo "Собран sing-box_linux_amd64"

      - name: Build sing-box for arm64
        run: |
          TAGS="with_gvisor,with_quic,with_dhcp,with_wireguard,with_utls,with_acme,with_clash_api,with_tailscale,with_v2ray_api"
          VERSION="${{ github.event.inputs.version || 'dev' }}-custom"
          GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -v -trimpath -tags "$TAGS" \
            -ldflags "-s -buildid= -X 'github.com/sagernet/sing-box/constant.Version=$VERSION'" \
            -o sing-box_linux_arm64 ./cmd/sing-box
          echo "Собран sing-box_linux_arm64"

      - name: Verify build artifacts
        run: |
          ls -l sing-box_linux_amd64 || echo "Ошибка: Файл sing-box_linux_amd64 не найден"
          ls -l sing-box_linux_arm64 || echo "Ошибка: Файл sing-box_linux_arm64 не найден"
          echo "Проверка артефактов завершена"

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version || 'nightly' }}
          name: sing-box ${{ github.event.inputs.version || 'nightly' }}
          files: |
            sing-box_linux_amd64
            sing-box_linux_arm64
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
