name: Build and Release sing-box

on:
  schedule:
    - cron: '0 0 * * *'  # Запуск каждый день в 00:00 UTC
  workflow_dispatch:    # Возможность ручного запуска

jobs:
  get-tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.get_tag.outputs.tag }}
    steps:
      - name: Get latest tag from SagerNet/sing-box
        id: get_tag
        run: |
          LATEST_TAG=$(curl -s https://api.github.com/repos/SagerNet/sing-box/releases/latest | jq -r .tag_name)
          echo "tag=$LATEST_TAG" >> $GITHUB_OUTPUT
          echo "Получен тег: $LATEST_TAG"

  build:
    needs: get-tag
    permissions:
      contents: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]  # Параллельная сборка для amd64 и arm64
    steps:
      - name: Checkout SagerNet/sing-box
        uses: actions/checkout@v4
        with:
          repository: SagerNet/sing-box
          ref: ${{ needs.get-tag.outputs.tag }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.24.3'

      - name: Download dependencies
        run: |
          go mod download
          echo "Зависимости загружены"

      - name: Build sing-box for ${{ matrix.arch }}
        run: |
          TAGS="with_gvisor,with_quic,with_dhcp,with_wireguard,with_utls,with_acme,with_clash_api,with_tailscale,with_v2ray_api"
          VERSION="${{ needs.get-tag.outputs.tag }}"
          GOOS=linux GOARCH=${{ matrix.arch }} CGO_ENABLED=0 go build -v -trimpath -tags "$TAGS" \
            -ldflags "-s -buildid= -X 'github.com/sagernet/sing-box/constant.Version=$VERSION'" \
            -o sing-box_linux_${{ matrix.arch }} ./cmd/sing-box
          echo "Собран sing-box_linux_${{ matrix.arch }}"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sing-box_linux_${{ matrix.arch }}
          path: sing-box_linux_${{ matrix.arch }}

  release:
    needs: [get-tag, build]
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.get-tag.outputs.tag }}
          name: sing-box ${{ needs.get-tag.outputs.tag }}
          files: |
            artifacts/sing-box_linux_amd64/sing-box_linux_amd64
            artifacts/sing-box_linux_arm64/sing-box_linux_arm64
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
